In [11]:
import numpy as np
x = np.array(["A",67,87])
print(x)
print(type(x))
print(x.dtype)

['A' '67' '87']
<class 'numpy.ndarray'>
<U11


In [13]:
import numpy as np
x = np.array([67,87])
print(x)
print(type(x))
print(x.dtype)

[67 87]
<class 'numpy.ndarray'>
int32


In [15]:
import numpy as np
x = np.array([9.2,67,87])
print(x)
print(type(x))
print(x.dtype)

[ 9.2 67.  87. ]
<class 'numpy.ndarray'>
float64


In [17]:
a2 = np.array([[20,30],[40,50]])
print(a2)
print(type(a2))
print(a2.shape)


[[20 30]
 [40 50]]
<class 'numpy.ndarray'>
(2, 2)


In [23]:
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [29]:
c = np.arange(1,7)
print(c)
type(c)

[1 2 3 4 5 6]


numpy.ndarray

In [35]:
d = np.array([1.345, 3.1232, 4.1234])
print(d)
print(np.around(np.sqrt(d),2))

[1.345  3.1232 4.1234]
[1.16 1.77 2.03]


In [39]:
a1 = np.array([[2,3,4,5],[6,5,4, np.NAN]])
print(a1)
print(a1.shape)
print(a1.dtype)

[[ 2.  3.  4.  5.]
 [ 6.  5.  4. nan]]
(2, 4)
float64


In [45]:
a1.reshape(4,2)

array([[ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  5.],
       [ 4., nan]])

In [47]:
a2 = np.array([[3,4,5],[5,6,4],[2,1,1]])
a2

array([[3, 4, 5],
       [5, 6, 4],
       [2, 1, 1]])

In [49]:
print(a2.sum(axis = 1))
print(a2.sum(axis=0))

[12 15  4]
[10 11 10]


In [51]:
a3 = np.array([[2,3,4],[3,4,5],[1,2,3]])
print(a3)
np.fill_diagonal(a3,0)
print(a3)

[[2 3 4]
 [3 4 5]
 [1 2 3]]
[[0 3 4]
 [3 0 5]
 [1 2 0]]
